### ISSUE TITLE
How to use  ?

### ISSUE THREAD

**Issue by liutianling** [MagedSaeed/farasapy#1]
After I download the package, then just input python setup.py ?

**Comment by MagedSaeed** [comment]
Dear @liutianling 

Thanks for your interest in the library. The library is still in its last development phases but will be available very soon. Maybe in a couple of days.

Stay tuned.

Many Thanks,

**Comment by liutianling** [comment]
@MagedSaeed Thank you very much for your so fast reply!
Thanks for your work!

**Comment by MagedSaeed** [comment]
@liutianling 

Please check README. I am going to close the issue.

**Comment by liutianling** [comment]
@MagedSaeed Greet!  I will have a try! Thanks.

**Comment by MagedSaeed** [comment]
@liutianling 

Great!
Waiting to hear your feedback. Thanks for your interest in this work.
