### ISSUE TITLE
Dependency parsing

### ISSUE THREAD

**Issue by Phd-Student2018** [MagedSaeed/farasapy#16]
Hi
How I can using Farasa to do dependency parsing in python(as your google notebook)
Thanks in advance

**Comment by MagedSaeed** [comment]
Hey @Phd-Student2018 , Thanks for your interest in the Farasapy.

Sorry for the late response, I was on vocation.

Can you please elaborate more on the problem, I did not quite get the issue clearly. What was missing? did you try it on your machine but it did not work out?

**Comment by MagedSaeed** [comment]
closing the issue for inactivity.

**Comment by ZOUHEIRBN** [comment]
Hello again! I have the same question
