### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by arwaa89** [MagedSaeed/farasapy#17]
i keep facing  erorrs when triyng to utilize python libraries designed for arabic language prprocessing.
 the last one is this error when i tried to use farasapy postagging 

`File "C:\Users\arwaa\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

is there a possible solution or it would be better if i run python on linux , not windows, because the other errorsi have faced turns out that it has to do with the system and the installation of the packages or the virtual environment  and not with the code itself, the codes are always correct

**Comment by MagedSaeed** [comment]
Hey @arwaa89 , thanks for reaching out and reporting the issue.

I would recomment first to try it on google.colab to check that the error is not from the code itself. Then, you may try to install brand new virtual environment and try again. If you are more interested, you can try WSL, Windows Subsystem for Linux, It may reslolve some of your problems.

**Comment by MagedSaeed** [comment]
closing the issue for inactivity.
