### ISSUE TITLE
dependency parser

### ISSUE THREAD

**Issue by GehadAboqamar** [MagedSaeed/farasapy#20]
How can I use the dependency parser in google colab (Python)?

and how can I use this in text relation?

**Comment by MagedSaeed** [comment]
Hey @GehadAboqamar 

Thanks for your interest in farasapy. Farasapy is a wrapper around many Java binaries provided by [qcri](https://farasa.qcri.org/). Unfortunately, they did not provide the dependency parser along with the binaries. The supported services are the ones listed and shown here, in this notebook:

https://colab.research.google.com/drive/1xjzYwmfAszNzfR6Z2lSQi3nKYcjarXAW

If you could contact them and manage to add the dependency parser to the binaries they are providing, I will happily integrate. You can cc me in your e-mails if you wish.

**Comment by GehadAboqamar** [comment]
Hey @MagedSaeed 

Thanks for your answer. 

ok, I send an email.
