### ISSUE TITLE
"Internal Error" return code: 1 when using FarasaStemmer

### ISSUE THREAD

**Issue by PyFiSciFi** [MagedSaeed/farasapy#7]
Thank you for creating this wrapper. 

When running the stemmer on anything (a small sample or in a lambda function), it says 

>perform system check...
>check java version...
Your java version is 1.8 which is compatiple with Farasa 
check toolkit binaries...
Dependencies seem to be satisfied..
task [STEM] is initialized in STANDALONE mode...
error occured! 
**return code: 1**
Traceback (most recent call last):

>  File "C:\Users\Alex\Documents\World Religions\Islam\Hadith Studies\Computational\Syed Project\Hadith Import v6 Stemming.py", line 192, in <module>
    lemmatizer.stem('اسْتَوْكَفَ ثَلاثًا')

>  File "C:\Users\Alex\anaconda3\envs\working\lib\site-packages\farasa\stemmer.py", line 8, in stem
    return self._do_task(text=text)

 > File "C:\Users\Alex\anaconda3\envs\working\lib\site-packages\farasa\__base.py", line 162, in _do_task
    return self._do_task_standalone(strip_text)

  >File "C:\Users\Alex\anaconda3\envs\working\lib\site-packages\farasa\__base.py", line 155, in _do_task_standalone
    return self._run_task(btext=byted_strip_text)

>  File "C:\Users\Alex\anaconda3\envs\working\lib\site-packages\farasa\__base.py", line 129, in _run_task
    raise Exception('Internal Error occured!')

>**Exception: Internal Error occured!**

Do you have any idea what is happening? I am using spyder, I downloaded the binary for the stemmer while using anaconda prompt though.

**Comment by MagedSaeed** [comment]
Hey @PyFiSciFi, we discovered a bug in the library on windows machines. We, me and @hefengxian , are working on it. We shall update the pypi package soon. Stay tuned.

**Comment by hefengxian** [comment]
Please check my issue #4 , and i already submit PRs to solve the problem, please wait @MagedSaeed to update the pypi

**Comment by PyFiSciFi** [comment]
Okay great thank you both. Sorry, from a quick glance I couldn't tell issue #4 was the same as mine. (And I'm pretty new to doing things with GitHub). Thanks!

**Comment by MagedSaeed** [comment]
@PyFiSciFi , @hefengxian 

The pypi package is now updated. Please check and provide your feedback.
Thanks

**Comment by PyFiSciFi** [comment]
It works perfectly well! Thanks so much!
